[package]
name = "dissemination"
version = "0.1.0"
authors = ["akhilsb <akhilsai2712@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { package = "config", path="../config"}
types = { package = "types", path="../types"}
crypto = { package = "crypto", path="../crypto"}
tokio = { version = "1.0", features = ["full"] }
futures = "^0.3"
bytes = "1.0"
tokio-util = "0.6"
tokio-stream = "0.1"
serde = "1.0.70"
serde_json = "1.0" # For JSON serialization
log="*"
priority-queue="1"
fnv = "1"
num-traits = "0.2.19"


# Local randomness
rand = "0.6"
rand_core = "0.6.4"
rand_chacha = "0.3.1"

# Big Integers for field operations
num-bigint-dig = "0.4"
num-bigint = {version = "0.2.6", features = ["rand"]}

bincode = "1"
tcp-reliable-sender = { package = "tcp-reliable-sender", git = "https://github.com/libdist-rs/libnet-rs.git", tag = "v0.2.1" }
tcp-receiver = { package = "tcp-receiver", git = "https://github.com/libdist-rs/libnet-rs.git", tag = "v0.2.1" }
async-trait = "0"
futures-util = "0"

# Polynomial Operations with FFT
lambdaworks-math = "0.11.0"

# Data parallelism
rayon = "=1.10.0"